security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      json_login:
        check_path: login


  access_control:
    - { path: ^/security/register, roles: PUBLIC_ACCESS }
    - { path: ^/security/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
