<?php declare(strict_types=1);

namespace App\CharacterGenerator\Enum;

enum FemaleName: string
{
    case Adele = 'Adele';
    case Agatha = 'Agatha';
    case Agnes = 'Agnes';
    case Albertina = 'Albertina';
    case Almeda = 'Almeda';
    case Amelia = 'Amelia';
    case Anastasia = 'Anastasia';
    case Annabelle = 'Annabelle';
    case Asenath = 'Asenath';
    case Augusta = 'Augusta';
    case Barbara = 'Barbara';
    case Bernadette = 'Bernadette';
    case Bernice = 'Bernice';
    case Beryl = 'Beryl';
    case Beulah = 'Beulah';
    case Camilla = 'Camilla';
    case Carmen = 'Carmen';
    case Caroline = 'Caroline';
    case Cecilia = 'Cecilia';
    case Celeste = 'Celeste';
    case Charity = 'Charity';
    case Christina = 'Christina';
    case Clarissa = 'Clarissa';
    case Claudia = 'Claudia';
    case Constance = 'Constance';
    case Cordelia = 'Cordelia';
    case Cynthia = 'Cynthia';
    case Daisy = 'Daisy';
    case Dolores = 'Dolores';
    case Doris = 'Doris';
    case Edith = 'Edith';
    case Edna = 'Edna';
    case Eloise = 'Eloise';
    case Elsie = 'Elsie';
    case Estelle = 'Estelle';
    case Ethel = 'Ethel';
    case Eudora = 'Eudora';
    case Eugenie = 'Eugenie';
    case Eunice = 'Eunice';
    case Florence = 'Florence';
    case Frieda = 'Frieda';
    case Genevieve = 'Genevieve';
    case Gertrude = 'Gertrude';
    case Gladys = 'Gladys';
    case Gretchen = 'Gretchen';
    case Hannah = 'Hannah';
    case Henrietta = 'Henrietta';
    case Hoshea = 'Hoshea';
    case Ingrid = 'Ingrid';
    case Irene = 'Irene';
    case Iris = 'Iris';
    case Ivy = 'Ivy';
    case Jeanette = 'Jeanette';
    case Jezebel = 'Jezebel';
    case Josephine = 'Josephine';
    case Joyce = 'Joyce';
    case Juanita = 'Juanita';
    case Keziah = 'Keziah';
    case Laverne = 'Laverne';
    case Leonora = 'Leonora';
    case Letitia = 'Letitia';
    case Loretta = 'Loretta';
    case Lucretia = 'Lucretia';
    case Mabel = 'Mabel';
    case Madeleine = 'Madeleine';
    case Margery = 'Margery';
    case Marguerite = 'Marguerite';
    case Marjorie = 'Marjorie';
    case Matilda = 'Matilda';
    case Melinda = 'Melinda';
    case Melissa = 'Melissa';
    case Mercedes = 'Mercedes';
    case Mildred = 'Mildred';
    case Millicent = 'Millicent';
    case Muriel = 'Muriel';
    case Myrtle = 'Myrtle';
    case Naomi = 'Naomi';
    case Nora = 'Nora';
    case Octavia = 'Octavia';
    case Ophelia = 'Ophelia';
    case Pansy = 'Pansy';
    case Patience = 'Patience';
    case Pearle = 'Pearle';
    case Phoebe = 'Phoebe';
    case Phyllis = 'Phyllis';
    case Rosemary = 'Rosemary';
    case Ruby = 'Ruby';
    case Sadie = 'Sadie';
    case Selina = 'Selina';
    case Selma = 'Selma';
    case Sibyl = 'Sibyl';
    case Sylvia = 'Sylvia';
    case Tabitha = 'Tabitha';
    case Ursula = 'Ursula';
    case Veronica = 'Veronica';
    case Violet = 'Violet';
    case Virginia = 'Virginia';
    case Wanda = 'Wanda';
    case Wilhelmina = 'Wilhelmina';
    case Winifred = 'Winifred';

    public static function rand(): self
    {
        return self::cases()[random_int(0, count(self::cases()))-1];
    }
}