<?php declare(strict_types=1);

namespace App\CharacterGenerator\Enum;

enum Skill: int
{
    /*
    case CthulhuMythos  = 00;
    case CreditRating = 00;
    case Accounting = 05;
    case Acting = 05;
    case Anthropology = 01;
    case Appraise = 05;
    case Archaeology = 01;
    case ArtAndCraft = 05;
    case Astronomy = 01;
    case Axe = 15;
    case Biology = 01;
    case Botany = 01;
    case Bow = 15;
    case Brawl = 25;
    case Chainsaw = 10;
    case Charm = 15;
    case Chemistry = 01;
    case Climb = 20;
    case Cryptography = 01;
    case Disguise = 05;
    case Diving = 01;
    case DriveAuto = 20;
    case ElectricalRepair = 10;
    case FastTalk = 05;
    case Fighting = 25;
    case FineArt = 05;
    case Firearms = 20;
    case FirstAid = 30;
    case Flail = 10;
    case Flamethrower = 10;
    case Forensics = 05;
    case Forgery = 01;
    case Garrote = 15;
    case Geology = 01;
    case Handgun = 20;
    case HeavyWeapons = 10;
    case History = 05;
    case Intimidate = 15;
    case Jump = 20;
    case OtherLanguage = 01;
    case Law = 05;
    case LibraryUse = 20;
    case Listen = 20;
    case Locksmith = 01;
    case MachineGun = 10;
    case Mathematics = 01;
    case MechanicalRepair = 10;
    case Medicine = 01;
    case Meteorology = 01;
    case NaturalWorld = 10;
    case Navigate = 10;
    case Occult = 05;
    case OperateHeavyMachinery = 01;
    case Persuade = 10;
    case Pharmacy = 01;
    case Photography = 05;
    case Physics = 01;
    case Pilot = 01;
    case Psychoanalysis = 01;
    case Psychology = 10;
    case Ride = 05;
    case Rifle = 25;
    case Science = 01;
    case Shotgun = 25;
    case SleightOfHand = 10;
    case Spear = 20;
    case SpotHidden = 25;
    case Stealth = 20;
    case SubMachineGun = 15;
    case Survival = 10;
    case Sword = 20;
    case Swim = 20;
    case Throw = 20;
    case Track = 10;
    case Whip = 05;
    case Zoology = 01;
    */
}