<?php declare(strict_types=1);

namespace App\CharacterGenerator\Enum;

enum Surname: string
{
    case Abraham = 'Abraham';
    case Adler = 'Adler';
    case Ankins = 'Ankins';
    case Avery = 'Avery';
    case Barnham = 'Barnham';
    case Bentz = 'Bentz';
    case Bessler = 'Bessler';
    case Blakely = 'Blakely';
    case Bleeker = 'Bleeker';
    case Bouche = 'Bouche';
    case Bretz = 'Bretz';
    case Brock = 'Brock';
    case Buchman = 'Buchman';
    case Butts = 'Butts';
    case Caffey = 'Caffey';
    case Click = 'Click';
    case Cordova = 'Cordova';
    case Crabtree = 'Crabtree';
    case Crankovitch = 'Crankovitch';
    case Cuthburt = 'Cuthburt';
    case Cuttling = 'Cuttling';
    case Dorman = 'Dorman';
    case Eakley = 'Eakley';
    case Eddie = 'Eddie';
    case Elsner = 'Elsner';
    case Fandrick = 'Fandrick';
    case Farwell = 'Farwell';
    case Feigel = 'Feigel';
    case Felten = 'Felten';
    case Fenske = 'Fenske';
    case Fillman = 'Fillman';
    case Finley = 'Finley';
    case Firske = 'Firske';
    case Flanagan = 'Flanagan';
    case Franklin = 'Franklin';
    case Freeman = 'Freeman';
    case Frisbe = 'Frisbe';
    case Gore = 'Gore';
    case Greenwald = 'Greenwald';
    case Hahn = 'Hahn';
    case Hammermeister = 'Hammermeister';
    case Heminger = 'Heminger';
    case Hogue = 'Hogue';
    case Hollister = 'Hollister';
    case Kasper = 'Kasper';
    case Kisro = 'Kisro';
    case Kleeman = 'Kleeman';
    case Lake = 'Lake';
    case Levard = 'Levard';
    case Lockhart = 'Lockhart';
    case Luckstrim = 'Luckstrim';
    case Lynch = 'Lynch';
    case Madison = 'Madison';
    case Mantei = 'Mantei';
    case Marsh = 'Marsh';
    case McBurney = 'McBurney';
    case McCarney = 'McCarney';
    case Moses = 'Moses';
    case Nickels = 'Nickels';
    case ONeil = 'O\'Neil';
    case Olson = 'Olson';
    case Ozanich = 'Ozanich';
    case Patterson = 'Patterson';
    case Patzer = 'Patzer';
    case Peppin = 'Peppin';
    case Porter = 'Porter';
    case Posch = 'Posch';
    case Raslo = 'Raslo';
    case Razner = 'Razner';
    case Rifenberg = 'Rifenberg';
    case Riley = 'Riley';
    case Ripley = 'Ripley';
    case Rossini = 'Rossini';
    case Schiltgan = 'Schiltgan';
    case Schmidt = 'Schmidt';
    case Schroeder = 'Schroeder';
    case Schwartz = 'Schwartz';
    case Shane = 'Shane';
    case Shattuck = 'Shattuck';
    case Shea = 'Shea';
    case Slaughter = 'Slaughter';
    case Smith = 'Smith';
    case Speltzer = 'Speltzer';
    case Stimac = 'Stimac';
    case Strenburg = 'Strenburg';
    case Strong = 'Strong';
    case Swanson = 'Swanson';
    case Tillinghast = 'Tillinghast';
    case Traver = 'Traver';
    case Urton = 'Urton';
    case Vallier = 'Vallier';
    case Wagner = 'Wagner';
    case Walsted = 'Walsted';
    case Wang = 'Wang';
    case Warner = 'Warner';
    case Webber = 'Webber';
    case Welch = 'Welch';
    case Winters = 'Winters';
    case Yarbrough = 'Yarbrough';
    case Yeske = 'Yeske';

    public static function rand(): self
    {
        return self::cases()[random_int(0, count(self::cases()))-1];
    }
}